"""Add subject field to ContactMessage

Revision ID: be0b1a9da6a2
Revises: e1b0428e5cbd
Create Date: 2025-06-12 17:10:54.425972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be0b1a9da6a2'
down_revision = 'e1b0428e5cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
